# Generated by Django 4.2.4 on 2023-12-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(default='0000DT', max_length=7)),
                ('image', models.ImageField(upload_to='images/')),
                ('info_image1', models.ImageField(default=0, upload_to='images/')),
                ('info_image2', models.ImageField(default=0, upload_to='images/')),
                ('category', models.CharField(choices=[['1', 'phones'], ['2', 'computers'], ['3', 'games'], ['4', 'headphones'], ['5', 'soundcards'], ['6', 'microphones']], default='1', max_length=1)),
                ('caract', models.CharField(default='no caracters', max_length=500)),
            ],
        ),
    ]
