# Generated by Django 4.2.4 on 2024-01-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[['phones', 'phones'], ['computers', 'computers'], ['games', 'games'], ['headphones', 'headphones'], ['soundcards', 'soundcards'], ['microphones', 'microphones']], default='phones', max_length=11),
        ),
    ]
