# Generated by Django 4.2.4 on 2024-01-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[['phones', 'phones'], ['computers', 'computers'], ['games', 'games'], ['headphones', 'headphones'], ['soundcards', 'soundcards'], ['microphones', 'microphones']], default='phones', max_length=20),
        ),
    ]
